### ISSUE TITLE
DSS NRID Performance Issues: High Latency and Contention for ISA Queries

### ISSUE THREAD

**Issue by wing-utm-sharing-airspace** [interuss/dss#1241]
**Describe the bug**
When running the NRID USS Qualifier, we've noticed GET and PUT ISA operations returning DEADLINE EXCEEDED errors (taking longer than 10s).

<img width="973" height="507" alt="Image" src="https://github.com/user-attachments/assets/d7300a0e-9d52-4b44-bd9f-9f28d6e008f7" />

Looking at the CRDB console, I'm seeing a good amount of contention and transaction restarts around the same time.

<img width="975" height="422" alt="Image" src="https://github.com/user-attachments/assets/13527c39-51b5-43e5-a1c3-c520edbb170e" />

<img width="976" height="389" alt="Image" src="https://github.com/user-attachments/assets/37af7969-7add-4b2c-bef4-7f5840b38937" />

Should be noted we use this instance for SCD load testing as well but have primarily seen timeouts around NRID requests.

**To Reproduce**
This can be reproduced using the [NRID Heavy Traffic Concurrent](https://github.com/interuss/monitoring/blob/58d636e06c5f05011bc668aeee85fc5d4e439694/monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/heavy_traffic_concurrent.md) USS Qualifier test scenario - we can get a passing result occasionally but this scenario seems to be failing more often than not.

**Expected behavior**
I would expect the DSS to be able to handle USS Qualifier levels of traffic without excessive contention/timeouts.

**Additional context**
Logs from our DSS deployment around the time of some of these timeouts
[downloaded-logs-20250812-125143.json](https://github.com/user-attachments/files/21740856/downloaded-logs-20250812-125143.json)

**Comment by BenjaminPelletier** [comment]
Thanks for this report -- that looks like great info to me.  Interestingly, it seems like the problem is strongly linked to transaction restarts, but doesn't seem to be nearly as related to contention most of the time.  We don't see failures in the CI, but the CI does not yet use a multi-node cluster, some aspect of which is presumably responsible for the problem.  @barroco when you do deployment verification for a dss release next, could you make sure the verification tests include the mentioned scenario?  That way we can see if the problem is reproducible in general or if we need to pursue getting more deployment-specific information.  I'm happy to help construct an appropriate test configuration if that can help.

@mickmis or @the-glu do you have an ideas or suggestions on next troubleshooting steps before we make our own deployment to attempt to reproduce?  Glancing at the logs seems to suggest CRDB is compacting on at least one of the affected nodes at the relevant time (though I see compacting on a different node that never has problems also, so not definitive).  Can you check into what is supposed to happen (presumably CRDB is engineered to never have delays like this under normal circumstances, even when maintenance operations are being performed) and how this situation might differ from that?  Assuming compaction is the issue and putting aside that it shouldn't affect ops like this, can you guess whether we expect compaction to actually be needed very often during normal use of the DSS?  I would have expected we should not actually be putting that much stress on the system (even with "high" volume in the tests) and therefore I wouldn't have expected something like compaction to happen very often.  That seems inconsistent with the observation that the load tests fail most of the time if compaction or similar is responsible for the failures.

@wing-utm-sharing-airspace what version of DSS software is being used?

**Comment by BradNicolle** [comment]
We've identified a possible contributing factor - it appears that `subscriptions` garbage collection is not working correctly on the main instance seeing this issue. For example, counting the total number of `subscriptions`:
```
root@localhost:26257/rid> SELECT COUNT(*) FROM subscriptions;
  count
---------
  16388
(1 row)
```

Counting the total number of `subscriptions` older than today's date:
```
root@localhost:26257/rid> SELECT COUNT(*) FROM subscriptions WHERE ends_at < CURRENT_DATE;
  count
---------
  15577
(1 row)
```

The oldest `subscriptions` date back about 5 months:
```
root@localhost:26257/rid> SELECT ends_at FROM subscriptions ORDER BY ends_at ASC LIMIT 1;
             ends_at
---------------------------------
  2025-03-08 02:39:30.858141+00
(1 row)
```

Looking at the [garbage collector function](https://github.com/interuss/dss/blob/26c034ae397863031bc845cbba3b7558a4d3cec5/pkg/rid/store/cockroach/garbage_collector.go#L59-L78), it seems like this could only ever delete one subscription at a time and then return an error, as the loop returns `if subOut != nil`. We're not even seeing this error in the logs though - we just see `Successful delete expired records` every 30mins from [`main.go`](https://github.com/interuss/dss/blob/26c034ae397863031bc845cbba3b7558a4d3cec5/cmds/core-service/main.go#L404). So it seems like either [`ListExpiredSubscriptions`](https://github.com/interuss/dss/blob/26c034ae397863031bc845cbba3b7558a4d3cec5/pkg/rid/store/cockroach/subscriptions.go#L277-L296) is returning an empty list, or `DeleteSubscription` is not actually deleting and returning anything.

I haven't yet been able to gather any evidence that this large `subscriptions` list actually causes any of the issues we're seeing. It's conceivable though that a large `subscriptions` table could slow down queries enough to cause contention under load.

**Comment by mickmis** [comment]
> We also see 5xx errors (albeit at a lower rate) from scd-related APIs. Does the scd garbage collection work differently to rid? I couldn't find a reference to it in my brief search of the codebase.

Yes, see https://github.com/interuss/dss/tree/master/cmds/db-manager/cleanup for how to do it and #1074 for some additional context on the approach taken. TL;DR: for scd a CLI tool is available to perform the cleanup, which may be called manually or setup to be invoked by a scheduled job.

IMO having garbage collection not aligned between rid and scd stores is confusing and should be addressed in any case.

**Comment by mickmis** [comment]
For anyone investigating this issue: it is worth looking at the code on `interuss/dss/v0.19.0` tag and not on master as relevant changes happened in the meantime.

One of those changes being that we have in v.0.19.0 different store implementation depending on the version of the rid schema, and one of them (for schema versions < 4.0.0) always return an empty list when listing expired subscriptions:
https://github.com/interuss/dss/blob/2c0ff28842fe6b106b81c98a262827f2ee7d4372/pkg/rid/store/cockroach/subcriptions_v3.go#L277-L280
(the comment is actually wrong, versions 3.1.0 and 3.1.1 of the schema do have the `writer` column)
So, @BradNicolle could you check what is the version of your schema?  `SELECT schema_version FROM schema_versions` should do.

> That indicates to me that perhaps we're not even getting into that loop, or alternatively DeleteSubscription is returning nil for all records. 

This could be explained by the fact that you have a schema version 3.1.0 or 3.1.1.
Now that would not explain why only `instance-3` seems to have expired entities not cleaned up, except if that's the only instance creating them.

> It looks like DeleteSubscription is doing [some further filtering on the updated_at field](https://github.com/interuss/dss/blob/1a3bf7e4086798a250b821aa23e81cbd01880ea8/pkg/rid/store/cockroach/subscriptions.go#L204), so maybe the results are somehow excluded by that filter?

Since we are passing directly to `DeleteSubscription` the output of `ListExpiredSubscriptions`, I would expect not, although not impossible.

> This shows the same writer (i.e. instance-3) for all subscriptions in the DB, which seems strange as there are also two other localities (i.e. instance-1 and instance-2). The instance-3 locality does still exist in our cluster though, and is reporting the Successful delete expired records log as expected.

Could you check that the locality is correctly set on the instance? The issue could be explained if somehow the locality was left empty or wrong or changed at some point. It is set by the CLI flag `locality`.

**Comment by BradNicolle** [comment]
@mickmis - the RID schema version on that instance is `4.0.0`:
```
root@localhost:26257/rid> SELECT * FROM schema_versions;
  onerow_enforcer | schema_version
------------------+-----------------
         t        | v4.0.0
(1 row)
```

I've double-checked both the CLI flag reported by Kubernetes, but also by getting a shell on the instance and checking the process invocation i.e.:
```
/ # ps | cat
PID   USER     TIME  COMMAND
    1 root     20:25 core-service --accepted_jwt_audiences=<redacted>,<redacted> --addr=:8080 --cockroach_host=cockroachdb-balanced.dss-main --cockroach_port=26257 --cockroach_ssl_dir=/cockroach/cockroach-certs --cockroach_ssl_mode=verify-full --cockroach_user=root --dump_requests=true --enable_scd=true --garbage_collector_spec=@every 30m --gcp_prof_service_name= --jwks_endpoint=<redacted> --jwks_key_ids=1 --locality=instance-3 --public_key_files=
```

I've also compared that against the other instances, and their args only differ in the `accepted_jwt_audiences` and `locality` as expected.

It also appears that `instance-3` is still managing to write entries with its given `locality` indicating it is correctly configured as of today, e.g. the most recent row in `subscriptions` has:
```
|           starts_at           |            ends_at            |          updated_at           |
| 2025-08-26 02:29:48.009897+00 | 2025-08-26 02:32:48.009897+00 | 2025-08-26 02:29:48.465289+00 |
```

**Comment by mickmis** [comment]
In addition, what is the uptime of this instance? The version of the DB schema determined at runtime is queried once and remains the same throughout the life of the instance. If a migration was done while it was live, that could be an issue. Any chance this has happened?

**Comment by mickmis** [comment]
@BradNicolle thanks for the input. Following that I ended up reproducing locally the issue. I found that `stacktrace.Propagate` actually returns `nil` if `err` is `nil` :/ Which is the case here:
https://github.com/interuss/dss/blob/99bb24dba49b1992ac48c36add4e1c15b5af1787/pkg/rid/store/cockroach/garbage_collector.go#L67-L71

That explains why you only see _Successful delete expired records_ log entries from the garbage collector and why it only deletes a single entity at a time every 30 minutes. Since you have ~15k subscriptions, cleaning them up 1 at a time every 30 minutes would take roughly 1 year. And if there are any ISAs to clean, 1 of them would be cleaned up first. So I suspect those are actually getting very slowly cleaned up.

Could you confirm this is correct? E.g. by:
- count the number of ISAs and subscriptions of instance-3
- let a pass of garbage collector run in instance-3
- count again both ISAs and subscriptions of instance-3

There should be exactly 1 ISA or subscription less, assuming none was added or removed in the meantime by a client.

If correct that would make #1249 and possibly #1250 high priority. And hopefully that was the cause of your performance issues @BradNicolle.

**Comment by BradNicolle** [comment]
Great find, thanks! 

I can confirm that I have now observed this behaviour, i.e.
- wait until just before periodic garbage collection - 19255 subscriptions
- wait until just after garbage collection (as confirmed by logs) - 19254 subscriptions

There was no change in ISAs, because we currently only have a single ISA on this instance with `ends_at` far in the future.

**Comment by mickmis** [comment]
@BradNicolle thanks for the accurate reporting!

The fix was merged (#1253, thanks @the-glu). We still need to confirm this was actually the source of the performance issues. @BradNicolle @BenjaminPelletier how shall we proceed from there? I'd see two approaches:
1. Release a v0.19.1 hotfix with #1253 cherry-picked on top of v0.19.0 so that the image can be swapped in place
2. Release a v0.20.2 with all of the latest changes, possibly requiring more steps for upgrade (v0.19.0 is from last December)

**Comment by BenjaminPelletier** [comment]
@BradNicolle what path forward will help the most with ultimately resolving the issue?  In addition to mickmis's 1 and 2, there is a 3 of "include fix in next normal release" which would be the default lowest-effort path unless one of the other paths would enable resolving the issue sooner/more easily.

**Comment by BradNicolle** [comment]
@BenjaminPelletier @mickmis - we're in the process of updating to `v0.20.0`, so a `v0.20.2` patch release would be ideal. If the next normal release is on the order of ~weeks away, that would also be fine but potentially draws out the identification of the root cause (i.e. in case this doesn't fix the contention issue).

**Comment by mickmis** [comment]
> we're in the process of updating to `v0.20.0`, so a `v0.20.2` patch release would be ideal. If the next normal release is on the order of ~weeks away, that would also be fine but potentially draws out the identification of the root cause (i.e. in case this doesn't fix the contention issue).

@BradNicolle this slipped through the cracks, sorry about that. Is the need for a patch release still current?
